name: Pipeline DevSecOps Complet

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  pipeline_securite:
    runs-on: ubuntu-latest

    steps:
      # --- ÉTAPE 1 : Préparation ---
      - name: Récupération du code source
        uses: actions/checkout@v4

      # --- ÉTAPE 2 : Chasse aux secrets (Action Officielle Gitleaks) ---
      - name: Scanner les mots de passe et clés API (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- ÉTAPE 3 : Analyse statique du code (Action Officielle Semgrep) ---
      - name: Scanner le code source multilingue (Semgrep)
        uses: returntocorp/semgrep-action@v1
        with:
          # On donne la liste des dictionnaires à utiliser
          config: p/default
            

      # --- ÉTAPE 4 : Analyse des dépendances (Natif car Node.js est pré-installé) ---
      - name: Vérifier les vulnérabilités npm (Natif)
        run: npm audit --audit-level=high
        continue-on-error: true 

      # --- ÉTAPE 5 : Analyse approfondie (Action Officielle Trivy) ---
      - name: Scanner les failles mondiales connues (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'HIGH,CRITICAL'

      # --- ÉTAPE 6 : Déploiement Continu (CD) ---
      - name: Déployer sur Render en toute sécurité
        if: success() 
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}